# Site settings
title: This is Angelo
subtitle: Machine Learning Blog
email: wenyudu.vip@gmail.com
description: "A machine learning craftsmanship blog."
baseurl: ""
url: "https://ange1o.github.io"
github_username:  ange1o

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

analytics :
  provider : google
  google:
    tracking_id : 'UA-36138203-3'
  getclicky :
    site_id
